/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-primary": "#5c8bff",
                "tertiary-dim": "#5f4b73",
                "primary-dim": "#004bbc",
                "on-secondary-container": "#42526e",
                "on-secondary": "#f8f8ff",
                "tertiary-fixed-dim": "#dabfef",
                "secondary-dim": "#445470",
                primary: "#0f57d0",
                "on-tertiary-container": "#57426a",
                "on-primary-container": "#000000",
                outline: "#767b7f",
                "inverse-surface": "#0c0f10",
                "tertiary-fixed": "#e8cdfd",
                "inverse-on-surface": "#9b9d9f",
                "primary-fixed": "#4e83fe",
                "on-primary-fixed-variant": "#000e32",
                "outline-variant": "#adb3b7",
                "on-primary": "#f9f8ff",
                "primary-container": "#4e83fe",
                "surface-bright": "#f8f9fb",
                "error-container": "#fa746f",
                "on-tertiary-fixed": "#433056",
                "on-surface": "#2d3337",
                "on-primary-fixed": "#000000",
                "tertiary-container": "#e8cdfd",
                "surface-container-low": "#f1f4f7",
                "secondary-fixed-dim": "#c4d5f7",
                "on-error": "#fff7f6",
                "surface-container-highest": "#dee3e7",
                "surface-dim": "#d5dbdf",
                "on-tertiary-fixed-variant": "#614c74",
                "on-secondary-fixed-variant": "#4c5c78",
                "on-background": "#2d3337",
                "surface-tint": "#0f57d0",
                "error-dim": "#67040d",
                "secondary-container": "#d6e3ff",
                "surface-container-lowest": "#ffffff",
                tertiary: "#6c567f",
                "primary-fixed-dim": "#3f75f0",
                "surface-container-high": "#e4e9ec",
                "surface-container": "#ebeef1",
                "secondary-fixed": "#d6e3ff",
                background: "#f8f9fb",
                "on-surface-variant": "#5a6064",
                "surface-variant": "#dee3e7",
                "on-error-container": "#6e0a12",
                surface: "#f8f9fb",
                error: "#a83836",
                secondary: "#4f607c",
                "on-tertiary": "#fff6ff",
                "on-secondary-fixed": "#30405b",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1.5rem",
                full: "9999px",
            },
            fontFamily: {
                headline: ['"Plus Jakarta Sans"', "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
            },
        },
    },
    plugins: [],
};
